# Change these first
owner: Pierstoval # Your GitHub organization or username, where this repository lives
repo: my_upptime # The name of this repository

sites:
  - name: alex-rock.tech
    url: https://alex-rock.tech/en/
  - name: www.orbitale.io
    url: https://www.orbitale.io/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: pierstoval.github.io
  baseUrl: /my_upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "-"
  navbar:
    - title: Status
      href: /my_upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
